Importing the Header Files

In [28]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

In [29]:
Data = pd.read_csv("Churn_Modelling.csv")

In [30]:
Data.head(n=5)

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [31]:
Data.shape

(10000, 14)

In [32]:
Data.describe(include = "all")

RowNumber    CustomerId Surname   CreditScore Geography Gender  \
count   10000.00000  1.000000e+04   10000  10000.000000     10000  10000   
unique          NaN           NaN    2932           NaN         3      2   
top             NaN           NaN   Smith           NaN    France   Male   
freq            NaN           NaN      32           NaN      5014   5457   
mean     5000.50000  1.569094e+07     NaN    650.528800       NaN    NaN   
std      2886.89568  7.193619e+04     NaN     96.653299       NaN    NaN   
min         1.00000  1.556570e+07     NaN    350.000000       NaN    NaN   
25%      2500.75000  1.562853e+07     NaN    584.000000       NaN    NaN   
50%      5000.50000  1.569074e+07     NaN    652.000000       NaN    NaN   
75%      7500.25000  1.575323e+07     NaN    718.000000       NaN    NaN   
max     10000.00000  1.581569e+07     NaN    850.000000       NaN    NaN   

                 Age        Tenure        Balance  NumOfProducts    HasCrCard  \
count   10000.000000  10000.000000   10000.000000   10000.000000  10000.00000   
unique           NaN           NaN            NaN            NaN          NaN   
top              NaN           NaN            NaN            NaN          NaN   
freq             NaN           NaN            NaN            NaN          NaN   
mean       38.921800      5.012800   76485.889288       1.530200      0.70550   
std        10.487806      2.892174   62397.405202       0.581654      0.45584   
min        18.000000      0.000000       0.000000       1.000000      0.00000   
25%        32.000000      3.000000       0.000000       1.000000      0.00000   
50%        37.000000      5.000000   97198.540000       1.000000      1.00000   
75%        44.000000      7.000000  127644.240000       2.000000      1.00000   
max        92.000000     10.000000  250898.090000       4.000000      1.00000   

        IsActiveMember  EstimatedSalary        Exited  
count     10000.000000     10000.000000  10000.000000  
unique             NaN              NaN           NaN  
top                NaN              NaN           NaN  
freq               NaN              NaN           NaN  
mean          0.515100    100090.239881      0.203700  
std           0.499797     57510.492818      0.402769  
min           0.000000        11.580000      0.000000  
25%           0.000000     51002.110000      0.000000  
50%           1.000000    100193.915000      0.000000  
75%           1.000000    149388.247500      0.000000  
max           1.000000    199992.480000      1.000000

In [33]:
Data = Data.drop(labels=["RowNumber", "CustomerId", "Surname"],axis = 1)
Data.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1  
3          0               0         93826.63       0  
4          1               1         79084.10       0

In [34]:
from sklearn.preprocessing import LabelEncoder as LL

In [35]:
le1 = LL()
le2 = LL()

In [36]:
Data["Gender"] = le1.fit_transform(Data["Gender"])

In [38]:
Data.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France       0   42       2       0.00              1   
1          608     Spain       0   41       1   83807.86              1   
2          502    France       0   42       8  159660.80              3   
3          699    France       0   39       1       0.00              2   
4          850     Spain       0   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1  
3          0               0         93826.63       0  
4          1               1         79084.10       0

In [39]:
Data["Geography"] = le2.fit_transform(Data["Geography"])
Data.head()

CreditScore  Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619          0       0   42       2       0.00              1   
1          608          2       0   41       1   83807.86              1   
2          502          0       0   42       8  159660.80              3   
3          699          0       0   39       1       0.00              2   
4          850          2       0   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1  
3          0               0         93826.63       0  
4          1               1         79084.10       0

In [40]:
from sklearn.preprocessing import OneHotEncoder as OHE

In [52]:
x = Data.iloc[:, 0:10]
y = Data.iloc[:, -1]

In [57]:
x.head()

CreditScore  Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619          0       0   42       2       0.00              1   
1          608          2       0   41       1   83807.86              1   
2          502          0       0   42       8  159660.80              3   
3          699          0       0   39       1       0.00              2   
4          850          2       0   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1        101348.88  
1          0               1        112542.58  
2          1               0        113931.57  
3          0               0         93826.63  
4          1               1         79084.10

In [58]:
y.head()

0    1
1    0
2    1
3    0
4    0
Name: Exited, dtype: int64

In [61]:
ohe = OHE(sparse=False, categorical_features= [1])
x = ohe.fit_transform(x)

In [64]:
x

array([[1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [65]:
x_dummy = pd.DataFrame(x)
x_dummy.head()

0    1    2      3    4     5    6          7    8    9    10         11
0  1.0  0.0  0.0  619.0  0.0  42.0  2.0       0.00  1.0  1.0  1.0  101348.88
1  0.0  0.0  1.0  608.0  0.0  41.0  1.0   83807.86  1.0  0.0  1.0  112542.58
2  1.0  0.0  0.0  502.0  0.0  42.0  8.0  159660.80  3.0  1.0  0.0  113931.57
3  1.0  0.0  0.0  699.0  0.0  39.0  1.0       0.00  2.0  0.0  0.0   93826.63
4  0.0  0.0  1.0  850.0  0.0  43.0  2.0  125510.82  1.0  1.0  1.0   79084.10

In [68]:
x_dummy = x_dummy.drop(labels=[1],axis=1)
x_dummy.head()

0    2      3    4     5    6          7    8    9    10         11
0  1.0  0.0  619.0  0.0  42.0  2.0       0.00  1.0  1.0  1.0  101348.88
1  0.0  1.0  608.0  0.0  41.0  1.0   83807.86  1.0  0.0  1.0  112542.58
2  1.0  0.0  502.0  0.0  42.0  8.0  159660.80  3.0  1.0  0.0  113931.57
3  1.0  0.0  699.0  0.0  39.0  1.0       0.00  2.0  0.0  0.0   93826.63
4  0.0  1.0  850.0  0.0  43.0  2.0  125510.82  1.0  1.0  1.0   79084.10

In [71]:
from sklearn.preprocessing import StandardScaler as SS
Scaler = SS()
x_scaled = Scaler.fit_transform(x_dummy)
x_scaled

array([[ 0.99720391, -0.57380915, -0.32622142, ...,  0.64609167,
         0.97024255,  0.02188649],
       [-1.00280393,  1.74273971, -0.44003595, ..., -1.54776799,
         0.97024255,  0.21653375],
       [ 0.99720391, -0.57380915, -1.53679418, ...,  0.64609167,
        -1.03067011,  0.2406869 ],
       ...,
       [ 0.99720391, -0.57380915,  0.60498839, ..., -1.54776799,
         0.97024255, -1.00864308],
       [-1.00280393, -0.57380915,  1.25683526, ...,  0.64609167,
        -1.03067011, -0.12523071],
       [ 0.99720391, -0.57380915,  1.46377078, ...,  0.64609167,
        -1.03067011, -1.07636976]])

In [72]:
y

0       1
1       0
2       1
3       0
4       0
5       1
6       0
7       1
8       0
9       0
10      0
11      0
12      0
13      0
14      0
15      0
16      1
17      0
18      0
19      0
20      0
21      0
22      1
23      0
24      0
25      0
26      0
27      0
28      0
29      0
       ..
9970    0
9971    0
9972    0
9973    0
9974    0
9975    1
9976    0
9977    0
9978    0
9979    0
9980    0
9981    1
9982    1
9983    0
9984    0
9985    0
9986    0
9987    0
9988    0
9989    0
9990    0
9991    1
9992    0
9993    0
9994    0
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

In [73]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x_scaled, y, random_state=42, test_size = 0.2)

In [74]:
from sklearn.linear_model import LogisticRegression as LR
regressor = LR()
regressor.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [85]:
regressor.score(x_train,y_train)

0.811375

In [86]:
y_pred = regressor.predict(x_test)

In [87]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
cm

array([[1543,   64],
       [ 314,   79]], dtype=int64)

In [88]:
print((1543 + 79)/2000)

0.811


In [89]:
from sklearn.neighbors import KNeighborsClassifier
regressorknn = KNeighborsClassifier()
regressorknn.fit(x_test,y_test)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [90]:
regressorknn.score(x_train,y_train)

0.82075

In [91]:
y_knn = regressorknn.predict(x_test)

In [92]:
cm_knn = confusion_matrix(y_test,y_knn)
cm_knn

array([[1565,   42],
       [ 223,  170]], dtype=int64)

In [93]:
print((1565 + 170)/2000)

0.8675


In [94]:
from sklearn.svm import SVC
regressorsvc = SVC()
regressorsvc.fit(x_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [95]:
regressorsvc.score(x_train,y_train)

0.864

In [96]:
y_svc = regressorsvc.predict(x_test)
cm_svc = confusion_matrix(y_test,y_svc)
cm_svc

array([[1569,   38],
       [ 246,  147]], dtype=int64)

In [97]:
print((1569 + 147)/2000)

0.858


In [100]:
from sklearn.naive_bayes import GaussianNB
regressornvb = GaussianNB()
regressornvb.fit(x_train,y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [101]:
regressornvb.score(x_train,y_train)

0.831625

In [102]:
y_nvb = regressornvb.predict(x_test)

In [103]:
cm_nvb = confusion_matrix(y_test,y_nvb)
cm_nvb

array([[1561,   46],
       [ 288,  105]], dtype=int64)

In [104]:
print((1561 + 105)/2000)

0.833


In [105]:
from sklearn.tree import DecisionTreeClassifier
regressorTree = DecisionTreeClassifier()
regressorTree.fit(x_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [107]:
regressorTree.score(x_train,y_train)

1.0

In [108]:
y_dec = regressorTree.predict(x_test)
cm_tree = confusion_matrix(y_test,y_dec)
cm_tree

array([[1358,  249],
       [ 189,  204]], dtype=int64)

In [109]:
print((1358 + 204)/2000)

0.781


In [110]:
from sklearn.ensemble import RandomForestClassifier
regressorforest = RandomForestClassifier()
regressorforest.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [111]:
regressorforest.score(x_train,y_train)

0.983125

In [112]:
y_forest = regressorforest.predict(x_test)
cm_forest = confusion_matrix(y_test,y_forest)
cm_forest

array([[1540,   67],
       [ 234,  159]], dtype=int64)

In [113]:
print((1540 + 159)/2000)

0.8495


Making ANN

In [115]:
import keras

Using TensorFlow backend.


In [116]:
from keras.models import Sequential
from keras.layers import Dense

In [117]:
classifier = Sequential()

In [118]:
classifier.add(Dense(units=40, activation="relu", input_dim = 11))
classifier.add(Dense(units=40, activation="relu"))
classifier.add(Dense(units=40, activation="relu"))
classifier.add(Dense(units=1, activation="sigmoid"))

In [119]:
classifier.compile(optimizer="adam", loss="binary_crossentropy", metrics= ["accuracy"])

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


In [120]:
classifier.fit(x_train, y_train, batch_size = 32, epochs = 100)


Epoch 1/100
8000/8000 [==============================] - 3s 383us/step - loss: 0.4647 - accuracy: 0.7914
Epoch 2/100
8000/8000 [==============================] - 1s 80us/step - loss: 0.3734 - accuracy: 0.8447
Epoch 3/100
8000/8000 [==============================] - 1s 97us/step - loss: 0.3492 - accuracy: 0.8568
Epoch 4/100
8000/8000 [==============================] - 1s 122us/step - loss: 0.3422 - accuracy: 0.8584
Epoch 5/100
8000/8000 [==============================] - 1s 91us/step - loss: 0.3377 - accuracy: 0.8597
Epoch 6/100
8000/8000 [==============================] - 1s 106us/step - loss: 0.3339 - accuracy: 0.8654
Epoch 7/100
8000/8000 [==============================] - 1s 124us/step - loss: 0.3302 - accuracy: 0.8658
Epoch 8/100
8000/8000 [==============================] - 1s 102us/step - loss: 0.3269 - accuracy: 0.8643
Epoch 9/100
8000/8000 [==============================] - 1s 102us/step - loss: 0.3254 - accuracy: 0.8666
Epoch 10/100
8000/8000 [==============================] -

In [122]:
y_ann = classifier.predict(x_test)
y_ann = (y_ann > 0.5)
cm_ann = confusion_matrix(y_test,y_ann)
cm_ann

array([[1486,  121],
       [ 215,  178]], dtype=int64)

In [123]:
print((1486 + 178)/2000)

0.832
