In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

In [2]:
data = pd.read_csv("adult.csv")

In [3]:
data.head()

age  workclass  fnlwgt     education  educational-num      marital-status  \
0   25    Private  226802          11th                7       Never-married   
1   38    Private   89814       HS-grad                9  Married-civ-spouse   
2   28  Local-gov  336951    Assoc-acdm               12  Married-civ-spouse   
3   44    Private  160323  Some-college               10  Married-civ-spouse   
4   18        NaN  103497  Some-college               10       Never-married   

          occupation relationship   race  gender  capital-gain  capital-loss  \
0  Machine-op-inspct    Own-child  Black    Male             0             0   
1    Farming-fishing      Husband  White    Male             0             0   
2    Protective-serv      Husband  White    Male             0             0   
3  Machine-op-inspct      Husband  Black    Male          7688             0   
4                NaN    Own-child  White  Female             0             0   

   hours-per-week native-country income  
0              40  United-States  <=50K  
1              50  United-States  <=50K  
2              40  United-States   >50K  
3              40  United-States   >50K  
4              30  United-States  <=50K

In [4]:
data.shape

(48842, 15)

In [5]:
data.isnull().sum()

age                   0
workclass          2799
fnlwgt                0
education             0
educational-num       0
marital-status        0
occupation         2809
relationship          0
race                  0
gender                0
capital-gain          0
capital-loss          0
hours-per-week        0
native-country      857
income                0
dtype: int64

In [6]:
data.describe(include = "all")

age workclass        fnlwgt education  educational-num  \
count   48842.000000     46043  4.884200e+04     48842     48842.000000   
unique           NaN         8           NaN        16              NaN   
top              NaN   Private           NaN   HS-grad              NaN   
freq             NaN     33906           NaN     15784              NaN   
mean       38.643585       NaN  1.896641e+05       NaN        10.078089   
std        13.710510       NaN  1.056040e+05       NaN         2.570973   
min        17.000000       NaN  1.228500e+04       NaN         1.000000   
25%        28.000000       NaN  1.175505e+05       NaN         9.000000   
50%        37.000000       NaN  1.781445e+05       NaN        10.000000   
75%        48.000000       NaN  2.376420e+05       NaN        12.000000   
max        90.000000       NaN  1.490400e+06       NaN        16.000000   

            marital-status      occupation relationship   race gender  \
count                48842           46033        48842  48842  48842   
unique                   7              14            6      5      2   
top     Married-civ-spouse  Prof-specialty      Husband  White   Male   
freq                 22379            6172        19716  41762  32650   
mean                   NaN             NaN          NaN    NaN    NaN   
std                    NaN             NaN          NaN    NaN    NaN   
min                    NaN             NaN          NaN    NaN    NaN   
25%                    NaN             NaN          NaN    NaN    NaN   
50%                    NaN             NaN          NaN    NaN    NaN   
75%                    NaN             NaN          NaN    NaN    NaN   
max                    NaN             NaN          NaN    NaN    NaN   

        capital-gain  capital-loss  hours-per-week native-country income  
count   48842.000000  48842.000000    48842.000000          47985  48842  
unique           NaN           NaN             NaN             41      2  
top              NaN           NaN             NaN  United-States  <=50K  
freq             NaN           NaN             NaN          43832  37155  
mean     1079.067626     87.502314       40.422382            NaN    NaN  
std      7452.019058    403.004552       12.391444            NaN    NaN  
min         0.000000      0.000000        1.000000            NaN    NaN  
25%         0.000000      0.000000       40.000000            NaN    NaN  
50%         0.000000      0.000000       40.000000            NaN    NaN  
75%         0.000000      0.000000       45.000000            NaN    NaN  
max     99999.000000   4356.000000       99.000000            NaN    NaN

In [7]:
data["workclass"].unique()       

array(['Private', 'Local-gov', nan, 'Self-emp-not-inc', 'Federal-gov',
       'State-gov', 'Self-emp-inc', 'Without-pay', 'Never-worked'],
      dtype=object)

In [8]:
data["workclass"].isnull().sum()

2799

In [9]:
data.dropna(axis = 0, inplace = True)

In [10]:
data.isnull().sum()

age                0
workclass          0
fnlwgt             0
education          0
educational-num    0
marital-status     0
occupation         0
relationship       0
race               0
gender             0
capital-gain       0
capital-loss       0
hours-per-week     0
native-country     0
income             0
dtype: int64

In [11]:
data.shape

(45222, 15)

In [12]:
x = data.iloc[:, 0:14]
y = data.iloc[:, -1]

In [13]:
x.head()

age  workclass  fnlwgt     education  educational-num      marital-status  \
0   25    Private  226802          11th                7       Never-married   
1   38    Private   89814       HS-grad                9  Married-civ-spouse   
2   28  Local-gov  336951    Assoc-acdm               12  Married-civ-spouse   
3   44    Private  160323  Some-college               10  Married-civ-spouse   
5   34    Private  198693          10th                6       Never-married   

          occupation   relationship   race gender  capital-gain  capital-loss  \
0  Machine-op-inspct      Own-child  Black   Male             0             0   
1    Farming-fishing        Husband  White   Male             0             0   
2    Protective-serv        Husband  White   Male             0             0   
3  Machine-op-inspct        Husband  Black   Male          7688             0   
5      Other-service  Not-in-family  White   Male             0             0   

   hours-per-week native-country  
0              40  United-States  
1              50  United-States  
2              40  United-States  
3              40  United-States  
5              30  United-States

In [14]:
x.shape

(45222, 14)

In [15]:
x["workclass"].unique()

array(['Private', 'Local-gov', 'Self-emp-not-inc', 'Federal-gov',
       'State-gov', 'Self-emp-inc', 'Without-pay'], dtype=object)

In [16]:
x["education"].unique()

array(['11th', 'HS-grad', 'Assoc-acdm', 'Some-college', '10th',
       'Prof-school', '7th-8th', 'Bachelors', 'Masters', '5th-6th',
       'Assoc-voc', '9th', 'Doctorate', '12th', '1st-4th', 'Preschool'],
      dtype=object)

In [17]:
X = pd.get_dummies(x)

In [18]:
X.head()

age  fnlwgt  educational-num  capital-gain  capital-loss  hours-per-week  \
0   25  226802                7             0             0              40   
1   38   89814                9             0             0              50   
2   28  336951               12             0             0              40   
3   44  160323               10          7688             0              40   
5   34  198693                6             0             0              30   

   workclass_Federal-gov  workclass_Local-gov  workclass_Private  \
0                      0                    0                  1   
1                      0                    0                  1   
2                      0                    1                  0   
3                      0                    0                  1   
5                      0                    0                  1   

   workclass_Self-emp-inc  ...  native-country_Portugal  \
0                       0  ...                        0   
1                       0  ...                        0   
2                       0  ...                        0   
3                       0  ...                        0   
5                       0  ...                        0   

   native-country_Puerto-Rico  native-country_Scotland  native-country_South  \
0                           0                        0                     0   
1                           0                        0                     0   
2                           0                        0                     0   
3                           0                        0                     0   
5                           0                        0                     0   

   native-country_Taiwan  native-country_Thailand  \
0                      0                        0   
1                      0                        0   
2                      0                        0   
3                      0                        0   
5                      0                        0   

   native-country_Trinadad&Tobago  native-country_United-States  \
0                               0                             1   
1                               0                             1   
2                               0                             1   
3                               0                             1   
5                               0                             1   

   native-country_Vietnam  native-country_Yugoslavia  
0                       0                          0  
1                       0                          0  
2                       0                          0  
3                       0                          0  
5                       0                          0  

[5 rows x 104 columns]

In [19]:
X.columns

Index(['age', 'fnlwgt', 'educational-num', 'capital-gain', 'capital-loss',
       'hours-per-week', 'workclass_Federal-gov', 'workclass_Local-gov',
       'workclass_Private', 'workclass_Self-emp-inc',
       ...
       'native-country_Portugal', 'native-country_Puerto-Rico',
       'native-country_Scotland', 'native-country_South',
       'native-country_Taiwan', 'native-country_Thailand',
       'native-country_Trinadad&Tobago', 'native-country_United-States',
       'native-country_Vietnam', 'native-country_Yugoslavia'],
      dtype='object', length=104)

In [20]:
X.drop(labels = ["workclass_Without-pay", "education_Preschool", "marital-status_Never-married", "occupation_Other-service", "relationship_Not-in-family", "race_Asian-Pac-Islander", "gender_Male", "native-country_Peru"], axis = 1, inplace = True)

In [21]:
X.shape

(45222, 96)

In [22]:
Y = pd.get_dummies(y)

In [23]:
Y.head()

<=50K  >50K
0      1     0
1      1     0
2      0     1
3      0     1
5      1     0

In [24]:
Y.drop(labels = ["<=50K"],axis = 1, inplace = True)

In [25]:
Y.head()

>50K
0     0
1     0
2     1
3     1
5     0

In [26]:
from sklearn.preprocessing import StandardScaler as SS
scaler = SS()
X_Scaled = scaler.fit_transform(X)
X_Scaled

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:645: DataConversionWarning: Data with input dtype uint8, int64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:464: DataConversionWarning: Data with input dtype uint8, int64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)


array([[-1.02498291,  0.35088942, -1.22155881, ...,  0.30850579,
        -0.04288082, -0.02255794],
       [-0.04145504, -0.94587846, -0.43812161, ...,  0.30850579,
        -0.04288082, -0.02255794],
       [-0.79801494,  1.39359159,  0.73703421, ...,  0.30850579,
        -0.04288082, -0.02255794],
       ...,
       [ 1.47166476, -0.35805983, -0.43812161, ...,  0.30850579,
        -0.04288082, -0.02255794],
       [-1.25195088,  0.11127873, -0.43812161, ...,  0.30850579,
        -0.04288082, -0.02255794],
       [ 1.01772882,  0.92951628, -0.43812161, ...,  0.30850579,
        -0.04288082, -0.02255794]])

In [27]:
Y.head()

>50K
0     0
1     0
2     1
3     1
5     0

In [28]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X_Scaled, Y, random_state = 42, test_size = 0.2)

In [29]:
from sklearn.linear_model import LogisticRegression as LR
Classifier = LR()
Classifier.fit(x_train,y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [30]:
Classifier.score(x_train,y_train)

0.8485501838184482

In [31]:
y_pred_Logistic = Classifier.predict(x_test)

In [32]:
from sklearn.metrics import confusion_matrix
CM = confusion_matrix(y_test, y_pred_Logistic)
CM

array([[6376,  466],
       [ 881, 1322]], dtype=int64)

In [33]:
Classifier.score(x_test,y_test)

0.851077943615257

In [34]:
from sklearn.svm import SVC
ClassifierSVC = SVC()
ClassifierSVC.fit(x_train,y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [35]:
ClassifierSVC.score(x_train,y_train)

0.8590540951433231

In [36]:
y_pred_SVC = ClassifierSVC.predict(x_test)

In [37]:
CM_SVC = confusion_matrix(y_test, y_pred_SVC)
CM_SVC

array([[6408,  434],
       [ 916, 1287]], dtype=int64)

In [38]:
ClassifierSVC.score(x_test,y_test)

0.8507462686567164

In [39]:
from sklearn.neighbors import KNeighborsClassifier
ClassifierKNN = KNeighborsClassifier()
ClassifierKNN.fit(x_train,y_train)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [40]:
ClassifierKNN.score(x_train,y_train)

0.8701661276501644

In [43]:
y_pred_KNN = ClassifierKNN.predict(x_test)

In [45]:
CM_KNN = confusion_matrix(y_test,y_pred_KNN)
CM_KNN

array([[6181,  661],
       [ 960, 1243]], dtype=int64)

In [46]:
from sklearn.ensemble import RandomForestClassifier
ClassifierR = RandomForestClassifier()
ClassifierR.fit(x_train,y_train)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [47]:
ClassifierR.score(x_train,y_train)

0.9868977527158139

In [48]:
y_pred = ClassifierR.predict(x_test)

In [49]:
CM_R = confusion_matrix(y_test,y_pred)
CM_R

array([[6359,  483],
       [ 916, 1287]], dtype=int64)

In [51]:
ClassifierR.score(x_test,y_test)

0.8453289110005527

In [79]:
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score

In [90]:
Model = Sequential()

In [91]:
Model.add(Dense(128, activation = "relu", input_dim = 96))
Model.add(Dense(128, activation = "relu"))
Model.add(Dropout(rate = 0.19))
Model.add(Dense(128, activation = "relu"))
Model.add(Dense(1, activation = "sigmoid"))

In [92]:
Model.compile(optimizer = "adam", loss = "binary_crossentropy",metrics = ["accuracy"])

In [93]:
Model.fit(x_train,y_train, epochs = 50)

Epoch 1/50
36177/36177 [==============================] - 6s 161us/step - loss: 0.3537 - accuracy: 0.8344
Epoch 2/50
36177/36177 [==============================] - 6s 160us/step - loss: 0.3248 - accuracy: 0.8474
Epoch 3/50
36177/36177 [==============================] - 5s 135us/step - loss: 0.3171 - accuracy: 0.8526
Epoch 4/50
36177/36177 [==============================] - 5s 140us/step - loss: 0.3132 - accuracy: 0.8535
Epoch 5/50
36177/36177 [==============================] - 5s 139us/step - loss: 0.3101 - accuracy: 0.8561
Epoch 6/50
36177/36177 [==============================] - 5s 150us/step - loss: 0.3079 - accuracy: 0.8560
Epoch 7/50
36177/36177 [==============================] - 5s 131us/step - loss: 0.3042 - accuracy: 0.8580
Epoch 8/50
36177/36177 [==============================] - 5s 146us/step - loss: 0.3010 - accuracy: 0.8591
Epoch 9/50
36177/36177 [==============================] - 5s 151us/step - loss: 0.2971 - accuracy: 0.8605
Epoch 10/50
36177/36177 [=====================

In [95]:
Y_Pred = Model.predict(x_test)
Y_Pred = (Y_Pred >= 0.5)

In [96]:
mat = confusion_matrix(y_test, Y_Pred)

In [105]:
mat

array([[6233,  609],
       [ 833, 1370]], dtype=int64)

In [106]:
print((6233 + 1370)/(6233 + 1370 + 609 + 833))

0.8405749032614704


In [107]:
def fun():
    Model = Sequential()
    Model.add(Dense(128, activation = "relu", input_dim = 96))
    Model.add(Dense(128, activation = "relu"))
    Model.add(Dropout(rate = 0.19))
    Model.add(Dense(128, activation = "relu"))
    Model.add(Dense(1, activation = "sigmoid"))
    Model.compile(optimizer = "adam", loss = "binary_crossentropy",metrics = ["accuracy"])
    return Model

In [112]:
Global_Classifier = KerasClassifier(build_fn=fun)

In [116]:
accuracies = cross_val_score(Global_Classifier, x_train, y_train)

Epoch 1/1
12059/12059 [==============================] - 2s 147us/step
Epoch 1/1
12059/12059 [==============================] - 2s 142us/step
Epoch 1/1
12059/12059 [==============================] - 2s 154us/step


In [117]:
accuracies

array([0.8419438 , 0.84219253, 0.84036821])

In [118]:
print(accuracies)

[0.8419438  0.84219253 0.84036821]
