# Importing the Header Files

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

# Importing the Dataset

In [2]:
Data = pd.read_csv("Churn_Modelling.csv")
Data.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [3]:
Data.shape

(10000, 14)

In [4]:
Data.describe(include="all")

RowNumber    CustomerId Surname   CreditScore Geography Gender  \
count   10000.00000  1.000000e+04   10000  10000.000000     10000  10000   
unique          NaN           NaN    2932           NaN         3      2   
top             NaN           NaN   Smith           NaN    France   Male   
freq            NaN           NaN      32           NaN      5014   5457   
mean     5000.50000  1.569094e+07     NaN    650.528800       NaN    NaN   
std      2886.89568  7.193619e+04     NaN     96.653299       NaN    NaN   
min         1.00000  1.556570e+07     NaN    350.000000       NaN    NaN   
25%      2500.75000  1.562853e+07     NaN    584.000000       NaN    NaN   
50%      5000.50000  1.569074e+07     NaN    652.000000       NaN    NaN   
75%      7500.25000  1.575323e+07     NaN    718.000000       NaN    NaN   
max     10000.00000  1.581569e+07     NaN    850.000000       NaN    NaN   

                 Age        Tenure        Balance  NumOfProducts    HasCrCard  \
count   10000.000000  10000.000000   10000.000000   10000.000000  10000.00000   
unique           NaN           NaN            NaN            NaN          NaN   
top              NaN           NaN            NaN            NaN          NaN   
freq             NaN           NaN            NaN            NaN          NaN   
mean       38.921800      5.012800   76485.889288       1.530200      0.70550   
std        10.487806      2.892174   62397.405202       0.581654      0.45584   
min        18.000000      0.000000       0.000000       1.000000      0.00000   
25%        32.000000      3.000000       0.000000       1.000000      0.00000   
50%        37.000000      5.000000   97198.540000       1.000000      1.00000   
75%        44.000000      7.000000  127644.240000       2.000000      1.00000   
max        92.000000     10.000000  250898.090000       4.000000      1.00000   

        IsActiveMember  EstimatedSalary        Exited  
count     10000.000000     10000.000000  10000.000000  
unique             NaN              NaN           NaN  
top                NaN              NaN           NaN  
freq               NaN              NaN           NaN  
mean          0.515100    100090.239881      0.203700  
std           0.499797     57510.492818      0.402769  
min           0.000000        11.580000      0.000000  
25%           0.000000     51002.110000      0.000000  
50%           1.000000    100193.915000      0.000000  
75%           1.000000    149388.247500      0.000000  
max           1.000000    199992.480000      1.000000

In [5]:
x = Data.iloc[:, 3:13].values
y = Data.iloc[:, -1].values

In [6]:
x

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [7]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [8]:
x.shape

(10000, 10)

In [9]:
y.shape

(10000,)

# Categorical Variable Encoding

In [10]:
from sklearn.preprocessing import LabelEncoder as LE
le1 = LE()
le2 = LE()

In [11]:
x[:, 1] = le1.fit_transform(x[:, 1])
x[:, 2] = le2.fit_transform(x[:, 2])

In [12]:
x

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ...,
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

In [13]:
from sklearn.preprocessing import OneHotEncoder as OHE

In [14]:
ohe = OHE(sparse=False,categorical_features = [1,2])
x = ohe.fit_transform(x)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [15]:
x

array([[1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [16]:
Data_Dummies = pd.DataFrame(x)

In [17]:
Data_Dummies.head()

0    1    2    3    4      5     6    7          8    9    10   11  \
0  1.0  0.0  0.0  1.0  0.0  619.0  42.0  2.0       0.00  1.0  1.0  1.0   
1  0.0  0.0  1.0  1.0  0.0  608.0  41.0  1.0   83807.86  1.0  0.0  1.0   
2  1.0  0.0  0.0  1.0  0.0  502.0  42.0  8.0  159660.80  3.0  1.0  0.0   
3  1.0  0.0  0.0  1.0  0.0  699.0  39.0  1.0       0.00  2.0  0.0  0.0   
4  0.0  0.0  1.0  1.0  0.0  850.0  43.0  2.0  125510.82  1.0  1.0  1.0   

          12  
0  101348.88  
1  112542.58  
2  113931.57  
3   93826.63  
4   79084.10

In [18]:
x_dummy = Data_Dummies.iloc[:, [0,2,3,5,6,7,8,9,10,11,12]].values
x_dummy

array([[1.0000000e+00, 0.0000000e+00, 1.0000000e+00, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 1.0000000e+00, 1.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [1.0000000e+00, 0.0000000e+00, 1.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [1.0000000e+00, 0.0000000e+00, 1.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [1.0000000e+00, 0.0000000e+00, 1.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [28]:
x_dummy.shape

(10000, 11)

# Train_Test_Split

In [29]:
from sklearn.model_selection import train_test_split

In [30]:
x_train, x_test, y_train, y_test = train_test_split(x_dummy, y, test_size = 0.2, random_state=42)

# Standardization

In [31]:
from sklearn.preprocessing import StandardScaler as SS
scaler = SS()
x_train = scaler.fit_transform(x_train)
x_test = scaler.fit_transform(x_test)

# Make ANN

In [32]:
import keras
from keras.models import Sequential
from keras.layers import Dense

In [33]:
ANN = Sequential()

In [43]:
ANN.add(Dense(6, kernel_initializer = "uniform", activation = "relu", input_dim = 11))
ANN.add(Dense(6, kernel_initializer = "uniform", activation = "relu"))
ANN.add(Dense(1, activation = "sigmoid"))

In [44]:
ANN.compile(optimizer="adam", loss="binary_crossentropy", metrics = ["accuracy"])

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


In [45]:
ANN.fit(x_train, y_train, batch_size = 32, epochs = 100)


Epoch 1/100
8000/8000 [==============================] - 3s 401us/step - loss: 0.5722 - accuracy: 0.7945
Epoch 2/100
8000/8000 [==============================] - 1s 74us/step - loss: 0.4516 - accuracy: 0.7945
Epoch 3/100
8000/8000 [==============================] - 1s 76us/step - loss: 0.4365 - accuracy: 0.7945
Epoch 4/100
8000/8000 [==============================] - 1s 75us/step - loss: 0.4329 - accuracy: 0.7945
Epoch 5/100
8000/8000 [==============================] - 1s 75us/step - loss: 0.4299 - accuracy: 0.7945
Epoch 6/100
8000/8000 [==============================] - 1s 75us/step - loss: 0.4260 - accuracy: 0.7989
Epoch 7/100
8000/8000 [==============================] - 1s 75us/step - loss: 0.4198 - accuracy: 0.8286
Epoch 8/100
8000/8000 [==============================] - 1s 76us/step - loss: 0.4124 - accuracy: 0.8320
Epoch 9/100
8000/8000 [==============================] - 1s 75us/step - loss: 0.4081 - accuracy: 0.8339
Epoch 10/100
8000/8000 [==============================] - 1s 7

8000/8000 [==============================] - 1s 85us/step - loss: 0.3999 - accuracy: 0.8357
Epoch 78/100
8000/8000 [==============================] - 1s 95us/step - loss: 0.3989 - accuracy: 0.8351
Epoch 79/100
8000/8000 [==============================] - 1s 89us/step - loss: 0.3985 - accuracy: 0.8365
Epoch 80/100
8000/8000 [==============================] - 1s 84us/step - loss: 0.3985 - accuracy: 0.8359
Epoch 81/100
8000/8000 [==============================] - 1s 75us/step - loss: 0.3988 - accuracy: 0.8363
Epoch 82/100
8000/8000 [==============================] - 1s 76us/step - loss: 0.3986 - accuracy: 0.8360
Epoch 83/100
8000/8000 [==============================] - 1s 75us/step - loss: 0.3981 - accuracy: 0.8374
Epoch 84/100
8000/8000 [==============================] - 1s 75us/step - loss: 0.3986 - accuracy: 0.8360
Epoch 85/100
8000/8000 [==============================] - 1s 75us/step - loss: 0.3994 - accuracy: 0.8363
Epoch 86/100
8000/8000 [==============================] - 1s 75us/st

In [46]:
y_predict = ANN.predict(x_test)

In [48]:
y_predict = (y_predict > 0.5)

In [49]:
y_predict

array([[False],
       [False],
       [False],
       ...,
       [ True],
       [False],
       [False]])

In [50]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_predict)

In [51]:
cm

array([[1579,   28],
       [ 296,   97]], dtype=int64)

In [52]:
print((1579 + 97)/2000)

0.838
