In [51]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [52]:
Data = pd.read_csv("Restaurant_Reviews.tsv", delimiter = "\t", quoting = 3)
Data.head()

Review  Liked
0                           Wow... Loved this place.      1
1                                 Crust is not good.      0
2          Not tasty and the texture was just nasty.      0
3  Stopped by during the late May bank holiday of...      1
4  The selection on the menu was great and so wer...      1

In [53]:
Data.shape

(1000, 2)

In [54]:
import re
import nltk
nltk.download("stopwords")
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
corpus = []

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Yadav's\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [55]:
for i in range(1000):
    review = re.sub("[^a-zA-z]", " ", Data["Review"][i]).lower().split()
    ps = PorterStemmer()
    review = [ps.stem(word) for word in review if not word in set(stopwords.words("english"))]
    review = " ".join(review)
    corpus.append(review)

In [56]:
data = pd.DataFrame(corpus)
data

0
0                                       wow love place
1                                           crust good
2                                   tasti textur nasti
3    stop late may bank holiday rick steve recommen...
4                              select menu great price
5                              get angri want damn pho
6                                  honeslti tast fresh
7    potato like rubber could tell made ahead time ...
8                                            fri great
9                                          great touch
10                                       servic prompt
11                                       would go back
12        cashier care ever say still end wayyy overpr
13          tri cape cod ravoli chicken cranberri mmmm
14                      disgust pretti sure human hair
15                               shock sign indic cash
16                                    highli recommend
17                          waitress littl slow servic
18                      place worth time let alon vega
19                                                like
20                                       burritto blah
21                                           food amaz
22                                    servic also cute
23                     could care less interior beauti
24                                             perform
25               right red velvet cake ohhh stuff good
26                             never brought salad ask
27   hole wall great mexican street taco friendli s...
28   took hour get food tabl restaur food luke warm...
29                                worst salmon sashimi
..                                                 ...
970  immedi said want talk manag want talk guy shot...
971                                ambianc much better
972                  unfortun set us disapppoint entre
973                                          food good
974        server suck wait correct server heimer suck
975                             happen next pretti put
976    bad caus know famili own realli want like place
977                                         overpr get
978                           vomit bathroom mid lunch
979     kept look time soon becom minut yet still food
980      place eat circumst would ever return top list
981    start tuna sashimi brownish color obvious fresh
982                                        food averag
983  sure beat nacho movi would expect littl bit co...
984                               ha long bay bit flop
985  problem charg sandwich bigger subway sub offer...
986    shrimp unwrap live mile brushfir liter ice cold
987                     lack flavor seem undercook dri
988                         realli impress place close
989                       would avoid place stay mirag
990         refri bean came meal dri crusti food bland
991                         spend money time place els
992  ladi tabl next us found live green caterpillar...
993                                    present food aw
994                                    tell disappoint
995                      think food flavor textur lack
996                             appetit instantli gone
997                       overal impress would go back
998  whole experi underwhelm think go ninja sushi n...
999  wast enough life pour salt wound draw time too...

[1000 rows x 1 columns]

In [57]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
X = cv.fit_transform(corpus).toarray()

In [58]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [61]:
Y = Data.iloc[:, -1].values

In [62]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X = scaler.fit_transform(X)
X

array([[-0.09529814, -0.0316386 , -0.0316386 , ..., -0.0316386 ,
        -0.06337243, -0.05986843],
       [-0.09529814, -0.0316386 , -0.0316386 , ..., -0.0316386 ,
        -0.06337243, -0.05986843],
       [-0.09529814, -0.0316386 , -0.0316386 , ..., -0.0316386 ,
        -0.06337243, -0.05986843],
       ...,
       [-0.09529814, -0.0316386 , -0.0316386 , ..., -0.0316386 ,
        -0.06337243, -0.05986843],
       [-0.09529814, -0.0316386 , -0.0316386 , ..., -0.0316386 ,
        -0.06337243, -0.05986843],
       [-0.09529814, -0.0316386 , -0.0316386 , ..., -0.0316386 ,
        -0.06337243, -0.05986843]])

In [63]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, Y, random_state = 42, test_size = 0.2)

In [77]:
from sklearn.neighbors import KNeighborsClassifier
Classifier = KNeighborsClassifier()
Classifier.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [78]:
Classifier.score(x_train, y_train)

0.865

In [79]:
y_pred = Classifier.predict(x_test)

In [80]:
from sklearn.metrics import confusion_matrix as CM 
cm = CM(y_test, y_pred)
cm

array([[63, 33],
       [49, 55]], dtype=int64)

In [81]:
print((63 +  55)/(63 + 55 + 33 + 49))

0.59


In [82]:
Classifier.score(x_test, y_test)

0.59